IMAGE_NAME = "ubuntu/xenial64"
MASTER_IP = "192.168.205.10"
MASK = "192.168.205"
NODES = 1
NET_NAME = "vbox_k8s"

Vagrant.configure("2") do |config|

  config.ssh.insert_key = false
  config.vm.box = IMAGE_NAME
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 2
    vb.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
    vb.customize ['modifyvm', :id, '--natdnsproxy1', 'on']
  end

  config.vm.define "k8s.master" do |master|
      master.vm.box = IMAGE_NAME
      master.vm.network :private_network, ip: MASTER_IP, virtualbox__intnet: NET_NAME
      master.vm.hostname = "k8s-master"
      master.vm.provision "docker"
      master.vm.provision "shell", path: "./scripts/base.sh"
      master.vm.provision "shell", path: "./scripts/master.sh"
  end

  (1..NODES).each do |i|
    config.vm.define "k8s.node#{i}" do |node|
      node.vm.box = IMAGE_NAME
      node.vm.network :private_network, ip: "#{MASK}.#{i + 10}", virtualbox__intnet: NET_NAME
      node.vm.hostname = "node-#{i}"
      node.vm.provision "docker"
      node.vm.provision "shell", path: "./scripts/base.sh"
      node.vm.provision "shell", path: "./scripts/node.sh"
    end
  end

end
