IMAGE_NAME = "ubuntu/xenial64"
MASTER_IP = "192.168.205.10"
NODES = 1

Vagrant.configure("2") do |config|

  config.ssh.insert_key = false
  config.vm.box = IMAGE_NAME

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 2
  end

  config.vm.define "k8s.master" do |master|
      master.vm.box = IMAGE_NAME
      config.vm.network :private_network, ip: MASTER_IP
      master.vm.hostname = "k8s-master"
      config.vm.provision "docker"
      config.vm.provision "shell", path: "./scripts/base.sh"
      # config.vm.provision "shell", path: "./scripts/master.sh"
  end

  (1..NODES).each do |i|
    config.vm.define "k8s.node#{i}" do |node|
      node.vm.box = IMAGE_NAME
      node.vm.network :private_network, ip: "192.168.205.#{i + 10}"
      node.vm.hostname = "node-#{i}"
    config.vm.provision "docker"
    config.vm.provision "shell", path: "./scripts/base.sh"
    config.vm.provision "shell", path: "./scripts/node.sh"
    end
  end

end
