IMAGE_NAME = "ubuntu/xenial64"
MASTER_IP = "192.168.70.10"
MASK = "192.168.70"
NODES = 1
NET_NAME = "vbox_k8s"

Vagrant.configure("2") do |config|

  config.ssh.insert_key = false
  config.vm.box = IMAGE_NAME
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 2
  end

  config.vm.define "k8s.master_v2" do |master|
      master.vm.box = IMAGE_NAME
      master.vm.network :private_network, ip: MASTER_IP, virtualbox__intnet: NET_NAME

      master.vm.provision "ansible" do |ansible|
          ansible.playbook = "config/master-playbook.yml"
          ansible.extra_vars = {
              node_ip: MASTER_IP,
          }
          ansible.verbose  = true
      end
  end

  (1..NODES).each do |i|
    config.vm.define "k8s.node#{i}_v2" do |node|
      node.vm.box = IMAGE_NAME
      node.vm.network :private_network, ip: "#{MASK}.#{i + 10}", virtualbox__intnet: NET_NAME

      node.vm.provision "ansible" do |ansible|
          ansible.extra_vars = {
              node_ip: "#{MASK}.#{i + 10}",
          }
          ansible.verbose  = true
          ansible.playbook = "config/node-playbook.yml"
      end
    end
  end

end
